name: Build jupyter-terraform-ansible
on:
  push:
    branches:
      - 'main'
    paths:
      - "*"
      - "!README.md"
      - "!build.rb"
  schedule:
    - cron: "0 0 * * 0-6"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: jupyter/base-notebook:python-3.10.6
            tag: '3.10'
          - base: jupyter/base-notebook:python-3.9.12
            tag: '3.9'
          - base: jupyter/base-notebook:python-3.8.8
            tag: '3.8'
#           - base: jupyter/tensorflow-notebook:latest   # no supported Ubuntu 22.04
#             tag: latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./terraform-ansible/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jupyter-terraform-ansible:${{ matrix.tag }}
          build-args: |
            IMAGE=${{ matrix.base }}
